name: experian master

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1

      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/sittercity *.gem
